//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 2013-12-10 22:28:06
namespace Insurance_company.ServiceReference
{
    
    /// <summary>
    /// There are no comments for InsuranceCompanyEntities in the schema.
    /// </summary>
    public partial class InsuranceCompanyEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new InsuranceCompanyEntities object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public InsuranceCompanyEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "InsuranceCompanyModel", "Insurance_company.ServiceReference");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("Insurance_company.ServiceReference", global::System.StringComparison.Ordinal))
            {
                return string.Concat("InsuranceCompanyModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for AdressSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<AdressSet> AdressSet
        {
            get
            {
                if ((this._AdressSet == null))
                {
                    this._AdressSet = base.CreateQuery<AdressSet>("AdressSet");
                }
                return this._AdressSet;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<AdressSet> _AdressSet;
        /// <summary>
        /// There are no comments for CarSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<CarSet> CarSet
        {
            get
            {
                if ((this._CarSet == null))
                {
                    this._CarSet = base.CreateQuery<CarSet>("CarSet");
                }
                return this._CarSet;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<CarSet> _CarSet;
        /// <summary>
        /// There are no comments for ClientSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ClientSet> ClientSet
        {
            get
            {
                if ((this._ClientSet == null))
                {
                    this._ClientSet = base.CreateQuery<ClientSet>("ClientSet");
                }
                return this._ClientSet;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ClientSet> _ClientSet;
        /// <summary>
        /// There are no comments for EmployeeSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<EmployeeSet> EmployeeSet
        {
            get
            {
                if ((this._EmployeeSet == null))
                {
                    this._EmployeeSet = base.CreateQuery<EmployeeSet>("EmployeeSet");
                }
                return this._EmployeeSet;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<EmployeeSet> _EmployeeSet;
        /// <summary>
        /// There are no comments for HouseSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<HouseSet> HouseSet
        {
            get
            {
                if ((this._HouseSet == null))
                {
                    this._HouseSet = base.CreateQuery<HouseSet>("HouseSet");
                }
                return this._HouseSet;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<HouseSet> _HouseSet;
        /// <summary>
        /// There are no comments for PolicySet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<PolicySet> PolicySet
        {
            get
            {
                if ((this._PolicySet == null))
                {
                    this._PolicySet = base.CreateQuery<PolicySet>("PolicySet");
                }
                return this._PolicySet;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<PolicySet> _PolicySet;
        /// <summary>
        /// There are no comments for sysdiagrams in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((this._sysdiagrams == null))
                {
                    this._sysdiagrams = base.CreateQuery<sysdiagrams>("sysdiagrams");
                }
                return this._sysdiagrams;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<sysdiagrams> _sysdiagrams;
        /// <summary>
        /// There are no comments for AdressSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToAdressSet(AdressSet adressSet)
        {
            base.AddObject("AdressSet", adressSet);
        }
        /// <summary>
        /// There are no comments for CarSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCarSet(CarSet carSet)
        {
            base.AddObject("CarSet", carSet);
        }
        /// <summary>
        /// There are no comments for ClientSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToClientSet(ClientSet clientSet)
        {
            base.AddObject("ClientSet", clientSet);
        }
        /// <summary>
        /// There are no comments for EmployeeSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToEmployeeSet(EmployeeSet employeeSet)
        {
            base.AddObject("EmployeeSet", employeeSet);
        }
        /// <summary>
        /// There are no comments for HouseSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToHouseSet(HouseSet houseSet)
        {
            base.AddObject("HouseSet", houseSet);
        }
        /// <summary>
        /// There are no comments for PolicySet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToPolicySet(PolicySet policySet)
        {
            base.AddObject("PolicySet", policySet);
        }
        /// <summary>
        /// There are no comments for sysdiagrams in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"InsuranceCompanyModel\" xmlns=\"http://schemas.microsoft.com/ado/2009/1" +
                "1/edm\"><EntityType Name=\"AdressSet\"><Key><PropertyRef Name=\"AdressId\" /></Key><P" +
                "roperty Name=\"AdressId\" Type=\"Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPatte" +
                "rn=\"Identity\" xmlns:p6=\"http://schemas.microsoft.com/ado/2009/02/edm/annotation\"" +
                " /><Property Name=\"Town\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"Max\" Fixe" +
                "dLength=\"false\" Unicode=\"true\" /><Property Name=\"Street\" Type=\"Edm.String\" Nulla" +
                "ble=\"false\" MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=" +
                "\"HouseNumber\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"Max\" FixedLength=\"fa" +
                "lse\" Unicode=\"true\" /><Property Name=\"ZipCode\" Type=\"Edm.String\" Nullable=\"false" +
                "\" MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"true\" /><NavigationProperty Name=" +
                "\"HouseSet\" Relationship=\"InsuranceCompanyModel.FK_AdressSetHouseSet\" ToRole=\"Hou" +
                "seSet\" FromRole=\"AdressSet\" /><NavigationProperty Name=\"ClientSet\" Relationship=" +
                "\"InsuranceCompanyModel.FK_ClientAdress\" ToRole=\"ClientSet\" FromRole=\"AdressSet\" " +
                "/></EntityType><EntityType Name=\"CarSet\"><Key><PropertyRef Name=\"ObjectId\" /></K" +
                "ey><Property Name=\"ObjectId\" Type=\"Edm.Int32\" Nullable=\"false\" p6:StoreGenerated" +
                "Pattern=\"Identity\" xmlns:p6=\"http://schemas.microsoft.com/ado/2009/02/edm/annota" +
                "tion\" /><Property Name=\"Type\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"Max\"" +
                " FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"Brand\" Type=\"Edm.String\" N" +
                "ullable=\"false\" MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"true\" /><Property N" +
                "ame=\"Year\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"VinNumber\" Type=\"" +
                "Edm.String\" Nullable=\"false\" MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"true\" " +
                "/><Property Name=\"Engine\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"Max\" Fix" +
                "edLength=\"false\" Unicode=\"true\" /><Property Name=\"Policy_PolicyId\" Type=\"Edm.Int" +
                "32\" Nullable=\"false\" /><NavigationProperty Name=\"PolicySet\" Relationship=\"Insura" +
                "nceCompanyModel.FK_CarPolicy\" ToRole=\"PolicySet\" FromRole=\"CarSet\" /></EntityTyp" +
                "e><EntityType Name=\"ClientSet\"><Key><PropertyRef Name=\"ClientId\" /></Key><Proper" +
                "ty Name=\"ClientId\" Type=\"Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"I" +
                "dentity\" xmlns:p6=\"http://schemas.microsoft.com/ado/2009/02/edm/annotation\" /><P" +
                "roperty Name=\"Surname\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"Max\" FixedL" +
                "ength=\"false\" Unicode=\"true\" /><Property Name=\"Name\" Type=\"Edm.String\" Nullable=" +
                "\"false\" MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"PES" +
                "EL\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"Max\" FixedLength=\"false\" Unico" +
                "de=\"true\" /><Property Name=\"AdressAdressId\" Type=\"Edm.Int32\" Nullable=\"false\" />" +
                "<NavigationProperty Name=\"AdressSet\" Relationship=\"InsuranceCompanyModel.FK_Clie" +
                "ntAdress\" ToRole=\"AdressSet\" FromRole=\"ClientSet\" /><NavigationProperty Name=\"Po" +
                "licySet\" Relationship=\"InsuranceCompanyModel.FK_PolicyClient\" ToRole=\"PolicySet\"" +
                " FromRole=\"ClientSet\" /></EntityType><EntityType Name=\"EmployeeSet\"><Key><Proper" +
                "tyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" p6" +
                ":StoreGeneratedPattern=\"Identity\" xmlns:p6=\"http://schemas.microsoft.com/ado/200" +
                "9/02/edm/annotation\" /><Property Name=\"Login\" Type=\"Edm.String\" Nullable=\"false\"" +
                " MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"Password\" " +
                "Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"" +
                "true\" /><Property Name=\"Name\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"Max\"" +
                " FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"Surname\" Type=\"Edm.String\"" +
                " Nullable=\"false\" MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"true\" /><Property" +
                " Name=\"Role\" Type=\"Edm.String\" Nullable=\"false\" /></EntityType><EntityType Name=" +
                "\"HouseSet\"><Key><PropertyRef Name=\"ObjectId\" /></Key><Property Name=\"ObjectId\" T" +
                "ype=\"Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"h" +
                "ttp://schemas.microsoft.com/ado/2009/02/edm/annotation\" /><Property Name=\"Year\" " +
                "Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Size\" Type=\"Edm.Int32\" Nulla" +
                "ble=\"false\" /><Property Name=\"Type\" Type=\"Edm.String\" Nullable=\"false\" MaxLength" +
                "=\"Max\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"Policy_PolicyId\" Typ" +
                "e=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"AdressSet_AdressId\" Type=\"Edm.I" +
                "nt32\" Nullable=\"false\" /><NavigationProperty Name=\"AdressSet\" Relationship=\"Insu" +
                "ranceCompanyModel.FK_AdressSetHouseSet\" ToRole=\"AdressSet\" FromRole=\"HouseSet\" /" +
                "><NavigationProperty Name=\"PolicySet\" Relationship=\"InsuranceCompanyModel.FK_Hou" +
                "sePolicy\" ToRole=\"PolicySet\" FromRole=\"HouseSet\" /></EntityType><EntityType Name" +
                "=\"PolicySet\"><Key><PropertyRef Name=\"PolicyId\" /></Key><Property Name=\"PolicyId\"" +
                " Type=\"Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=" +
                "\"http://schemas.microsoft.com/ado/2009/02/edm/annotation\" /><Property Name=\"Dura" +
                "tion\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"StartDate\" Type=\"Edm.D" +
                "ateTime\" Nullable=\"false\" Precision=\"3\" /><Property Name=\"EndDate\" Type=\"Edm.Dat" +
                "eTime\" Nullable=\"false\" Precision=\"3\" /><Property Name=\"ObjectType\" Type=\"Edm.St" +
                "ring\" Nullable=\"false\" MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"true\" /><Pro" +
                "perty Name=\"ClientClientId\" Type=\"Edm.Int32\" Nullable=\"false\" /><NavigationPrope" +
                "rty Name=\"CarSet\" Relationship=\"InsuranceCompanyModel.FK_CarPolicy\" ToRole=\"CarS" +
                "et\" FromRole=\"PolicySet\" /><NavigationProperty Name=\"ClientSet\" Relationship=\"In" +
                "suranceCompanyModel.FK_PolicyClient\" ToRole=\"ClientSet\" FromRole=\"PolicySet\" /><" +
                "NavigationProperty Name=\"HouseSet\" Relationship=\"InsuranceCompanyModel.FK_HouseP" +
                "olicy\" ToRole=\"HouseSet\" FromRole=\"PolicySet\" /></EntityType><EntityType Name=\"s" +
                "ysdiagrams\"><Key><PropertyRef Name=\"diagram_id\" /></Key><Property Name=\"name\" Ty" +
                "pe=\"Edm.String\" Nullable=\"false\" MaxLength=\"128\" FixedLength=\"false\" Unicode=\"tr" +
                "ue\" /><Property Name=\"principal_id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Propert" +
                "y Name=\"diagram_id\" Type=\"Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"" +
                "Identity\" xmlns:p6=\"http://schemas.microsoft.com/ado/2009/02/edm/annotation\" /><" +
                "Property Name=\"version\" Type=\"Edm.Int32\" /><Property Name=\"definition\" Type=\"Edm" +
                ".Binary\" MaxLength=\"Max\" FixedLength=\"false\" /></EntityType><Association Name=\"F" +
                "K_AdressSetHouseSet\"><End Type=\"InsuranceCompanyModel.AdressSet\" Role=\"AdressSet" +
                "\" Multiplicity=\"1\" /><End Type=\"InsuranceCompanyModel.HouseSet\" Role=\"HouseSet\" " +
                "Multiplicity=\"*\" /><ReferentialConstraint><Principal Role=\"AdressSet\"><PropertyR" +
                "ef Name=\"AdressId\" /></Principal><Dependent Role=\"HouseSet\"><PropertyRef Name=\"A" +
                "dressSet_AdressId\" /></Dependent></ReferentialConstraint></Association><Associat" +
                "ion Name=\"FK_ClientAdress\"><End Type=\"InsuranceCompanyModel.AdressSet\" Role=\"Adr" +
                "essSet\" Multiplicity=\"1\" /><End Type=\"InsuranceCompanyModel.ClientSet\" Role=\"Cli" +
                "entSet\" Multiplicity=\"*\" /><ReferentialConstraint><Principal Role=\"AdressSet\"><P" +
                "ropertyRef Name=\"AdressId\" /></Principal><Dependent Role=\"ClientSet\"><PropertyRe" +
                "f Name=\"AdressAdressId\" /></Dependent></ReferentialConstraint></Association><Ass" +
                "ociation Name=\"FK_CarPolicy\"><End Type=\"InsuranceCompanyModel.PolicySet\" Role=\"P" +
                "olicySet\" Multiplicity=\"1\" /><End Type=\"InsuranceCompanyModel.CarSet\" Role=\"CarS" +
                "et\" Multiplicity=\"*\" /><ReferentialConstraint><Principal Role=\"PolicySet\"><Prope" +
                "rtyRef Name=\"PolicyId\" /></Principal><Dependent Role=\"CarSe";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart1 = "t\"><PropertyRef Name=\"Policy_PolicyId\" /></Dependent></ReferentialConstraint></As" +
                "sociation><Association Name=\"FK_PolicyClient\"><End Type=\"InsuranceCompanyModel.C" +
                "lientSet\" Role=\"ClientSet\" Multiplicity=\"1\" /><End Type=\"InsuranceCompanyModel.P" +
                "olicySet\" Role=\"PolicySet\" Multiplicity=\"*\" /><ReferentialConstraint><Principal " +
                "Role=\"ClientSet\"><PropertyRef Name=\"ClientId\" /></Principal><Dependent Role=\"Pol" +
                "icySet\"><PropertyRef Name=\"ClientClientId\" /></Dependent></ReferentialConstraint" +
                "></Association><Association Name=\"FK_HousePolicy\"><End Type=\"InsuranceCompanyMod" +
                "el.PolicySet\" Role=\"PolicySet\" Multiplicity=\"1\" /><End Type=\"InsuranceCompanyMod" +
                "el.HouseSet\" Role=\"HouseSet\" Multiplicity=\"*\" /><ReferentialConstraint><Principa" +
                "l Role=\"PolicySet\"><PropertyRef Name=\"PolicyId\" /></Principal><Dependent Role=\"H" +
                "ouseSet\"><PropertyRef Name=\"Policy_PolicyId\" /></Dependent></ReferentialConstrai" +
                "nt></Association></Schema><Schema Namespace=\"Service\" xmlns=\"http://schemas.micr" +
                "osoft.com/ado/2009/11/edm\"><EntityContainer Name=\"InsuranceCompanyEntities\" m:Is" +
                "DefaultEntityContainer=\"true\" p6:LazyLoadingEnabled=\"true\" xmlns:p6=\"http://sche" +
                "mas.microsoft.com/ado/2009/02/edm/annotation\"><EntitySet Name=\"AdressSet\" Entity" +
                "Type=\"InsuranceCompanyModel.AdressSet\" /><EntitySet Name=\"CarSet\" EntityType=\"In" +
                "suranceCompanyModel.CarSet\" /><EntitySet Name=\"ClientSet\" EntityType=\"InsuranceC" +
                "ompanyModel.ClientSet\" /><EntitySet Name=\"EmployeeSet\" EntityType=\"InsuranceComp" +
                "anyModel.EmployeeSet\" /><EntitySet Name=\"HouseSet\" EntityType=\"InsuranceCompanyM" +
                "odel.HouseSet\" /><EntitySet Name=\"PolicySet\" EntityType=\"InsuranceCompanyModel.P" +
                "olicySet\" /><EntitySet Name=\"sysdiagrams\" EntityType=\"InsuranceCompanyModel.sysd" +
                "iagrams\" /><AssociationSet Name=\"FK_AdressSetHouseSet\" Association=\"InsuranceCom" +
                "panyModel.FK_AdressSetHouseSet\"><End Role=\"AdressSet\" EntitySet=\"AdressSet\" /><E" +
                "nd Role=\"HouseSet\" EntitySet=\"HouseSet\" /></AssociationSet><AssociationSet Name=" +
                "\"FK_ClientAdress\" Association=\"InsuranceCompanyModel.FK_ClientAdress\"><End Role=" +
                "\"AdressSet\" EntitySet=\"AdressSet\" /><End Role=\"ClientSet\" EntitySet=\"ClientSet\" " +
                "/></AssociationSet><AssociationSet Name=\"FK_CarPolicy\" Association=\"InsuranceCom" +
                "panyModel.FK_CarPolicy\"><End Role=\"CarSet\" EntitySet=\"CarSet\" /><End Role=\"Polic" +
                "ySet\" EntitySet=\"PolicySet\" /></AssociationSet><AssociationSet Name=\"FK_PolicyCl" +
                "ient\" Association=\"InsuranceCompanyModel.FK_PolicyClient\"><End Role=\"ClientSet\" " +
                "EntitySet=\"ClientSet\" /><End Role=\"PolicySet\" EntitySet=\"PolicySet\" /></Associat" +
                "ionSet><AssociationSet Name=\"FK_HousePolicy\" Association=\"InsuranceCompanyModel." +
                "FK_HousePolicy\"><End Role=\"HouseSet\" EntitySet=\"HouseSet\" /><End Role=\"PolicySet" +
                "\" EntitySet=\"PolicySet\" /></AssociationSet></EntityContainer></Schema></edmx:Dat" +
                "aServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0, ModelPart1);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for InsuranceCompanyModel.AdressSet in the schema.
    /// </summary>
    /// <KeyProperties>
    /// AdressId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("AdressSet")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("AdressId")]
    public partial class AdressSet : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new AdressSet object.
        /// </summary>
        /// <param name="adressId">Initial value of AdressId.</param>
        /// <param name="town">Initial value of Town.</param>
        /// <param name="street">Initial value of Street.</param>
        /// <param name="houseNumber">Initial value of HouseNumber.</param>
        /// <param name="zipCode">Initial value of ZipCode.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static AdressSet CreateAdressSet(int adressId, string town, string street, string houseNumber, string zipCode)
        {
            AdressSet adressSet = new AdressSet();
            adressSet.AdressId = adressId;
            adressSet.Town = town;
            adressSet.Street = street;
            adressSet.HouseNumber = houseNumber;
            adressSet.ZipCode = zipCode;
            return adressSet;
        }
        /// <summary>
        /// There are no comments for Property AdressId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int AdressId
        {
            get
            {
                return this._AdressId;
            }
            set
            {
                this.OnAdressIdChanging(value);
                this._AdressId = value;
                this.OnAdressIdChanged();
                this.OnPropertyChanged("AdressId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _AdressId;
        partial void OnAdressIdChanging(int value);
        partial void OnAdressIdChanged();
        /// <summary>
        /// There are no comments for Property Town in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Town
        {
            get
            {
                return this._Town;
            }
            set
            {
                this.OnTownChanging(value);
                this._Town = value;
                this.OnTownChanged();
                this.OnPropertyChanged("Town");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Town;
        partial void OnTownChanging(string value);
        partial void OnTownChanged();
        /// <summary>
        /// There are no comments for Property Street in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Street
        {
            get
            {
                return this._Street;
            }
            set
            {
                this.OnStreetChanging(value);
                this._Street = value;
                this.OnStreetChanged();
                this.OnPropertyChanged("Street");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Street;
        partial void OnStreetChanging(string value);
        partial void OnStreetChanged();
        /// <summary>
        /// There are no comments for Property HouseNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string HouseNumber
        {
            get
            {
                return this._HouseNumber;
            }
            set
            {
                this.OnHouseNumberChanging(value);
                this._HouseNumber = value;
                this.OnHouseNumberChanged();
                this.OnPropertyChanged("HouseNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _HouseNumber;
        partial void OnHouseNumberChanging(string value);
        partial void OnHouseNumberChanged();
        /// <summary>
        /// There are no comments for Property ZipCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ZipCode
        {
            get
            {
                return this._ZipCode;
            }
            set
            {
                this.OnZipCodeChanging(value);
                this._ZipCode = value;
                this.OnZipCodeChanged();
                this.OnPropertyChanged("ZipCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ZipCode;
        partial void OnZipCodeChanging(string value);
        partial void OnZipCodeChanged();
        /// <summary>
        /// There are no comments for HouseSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<HouseSet> HouseSet
        {
            get
            {
                return this._HouseSet;
            }
            set
            {
                this._HouseSet = value;
                this.OnPropertyChanged("HouseSet");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<HouseSet> _HouseSet = new global::System.Data.Services.Client.DataServiceCollection<HouseSet>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for ClientSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<ClientSet> ClientSet
        {
            get
            {
                return this._ClientSet;
            }
            set
            {
                this._ClientSet = value;
                this.OnPropertyChanged("ClientSet");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<ClientSet> _ClientSet = new global::System.Data.Services.Client.DataServiceCollection<ClientSet>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for InsuranceCompanyModel.CarSet in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ObjectId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("CarSet")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ObjectId")]
    public partial class CarSet : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new CarSet object.
        /// </summary>
        /// <param name="objectId">Initial value of ObjectId.</param>
        /// <param name="type">Initial value of Type.</param>
        /// <param name="brand">Initial value of Brand.</param>
        /// <param name="year">Initial value of Year.</param>
        /// <param name="vinNumber">Initial value of VinNumber.</param>
        /// <param name="engine">Initial value of Engine.</param>
        /// <param name="policy_PolicyId">Initial value of Policy_PolicyId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static CarSet CreateCarSet(int objectId, string type, string brand, int year, string vinNumber, string engine, int policy_PolicyId)
        {
            CarSet carSet = new CarSet();
            carSet.ObjectId = objectId;
            carSet.Type = type;
            carSet.Brand = brand;
            carSet.Year = year;
            carSet.VinNumber = vinNumber;
            carSet.Engine = engine;
            carSet.Policy_PolicyId = policy_PolicyId;
            return carSet;
        }
        /// <summary>
        /// There are no comments for Property ObjectId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ObjectId
        {
            get
            {
                return this._ObjectId;
            }
            set
            {
                this.OnObjectIdChanging(value);
                this._ObjectId = value;
                this.OnObjectIdChanged();
                this.OnPropertyChanged("ObjectId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ObjectId;
        partial void OnObjectIdChanging(int value);
        partial void OnObjectIdChanged();
        /// <summary>
        /// There are no comments for Property Type in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Type
        {
            get
            {
                return this._Type;
            }
            set
            {
                this.OnTypeChanging(value);
                this._Type = value;
                this.OnTypeChanged();
                this.OnPropertyChanged("Type");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Type;
        partial void OnTypeChanging(string value);
        partial void OnTypeChanged();
        /// <summary>
        /// There are no comments for Property Brand in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Brand
        {
            get
            {
                return this._Brand;
            }
            set
            {
                this.OnBrandChanging(value);
                this._Brand = value;
                this.OnBrandChanged();
                this.OnPropertyChanged("Brand");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Brand;
        partial void OnBrandChanging(string value);
        partial void OnBrandChanged();
        /// <summary>
        /// There are no comments for Property Year in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Year
        {
            get
            {
                return this._Year;
            }
            set
            {
                this.OnYearChanging(value);
                this._Year = value;
                this.OnYearChanged();
                this.OnPropertyChanged("Year");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Year;
        partial void OnYearChanging(int value);
        partial void OnYearChanged();
        /// <summary>
        /// There are no comments for Property VinNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string VinNumber
        {
            get
            {
                return this._VinNumber;
            }
            set
            {
                this.OnVinNumberChanging(value);
                this._VinNumber = value;
                this.OnVinNumberChanged();
                this.OnPropertyChanged("VinNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _VinNumber;
        partial void OnVinNumberChanging(string value);
        partial void OnVinNumberChanged();
        /// <summary>
        /// There are no comments for Property Engine in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Engine
        {
            get
            {
                return this._Engine;
            }
            set
            {
                this.OnEngineChanging(value);
                this._Engine = value;
                this.OnEngineChanged();
                this.OnPropertyChanged("Engine");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Engine;
        partial void OnEngineChanging(string value);
        partial void OnEngineChanged();
        /// <summary>
        /// There are no comments for Property Policy_PolicyId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Policy_PolicyId
        {
            get
            {
                return this._Policy_PolicyId;
            }
            set
            {
                this.OnPolicy_PolicyIdChanging(value);
                this._Policy_PolicyId = value;
                this.OnPolicy_PolicyIdChanged();
                this.OnPropertyChanged("Policy_PolicyId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Policy_PolicyId;
        partial void OnPolicy_PolicyIdChanging(int value);
        partial void OnPolicy_PolicyIdChanged();
        /// <summary>
        /// There are no comments for PolicySet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public PolicySet PolicySet
        {
            get
            {
                return this._PolicySet;
            }
            set
            {
                this._PolicySet = value;
                this.OnPropertyChanged("PolicySet");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private PolicySet _PolicySet;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for InsuranceCompanyModel.ClientSet in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ClientId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("ClientSet")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ClientId")]
    public partial class ClientSet : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ClientSet object.
        /// </summary>
        /// <param name="clientId">Initial value of ClientId.</param>
        /// <param name="surname">Initial value of Surname.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="pESEL">Initial value of PESEL.</param>
        /// <param name="adressAdressId">Initial value of AdressAdressId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ClientSet CreateClientSet(int clientId, string surname, string name, string pESEL, int adressAdressId)
        {
            ClientSet clientSet = new ClientSet();
            clientSet.ClientId = clientId;
            clientSet.Surname = surname;
            clientSet.Name = name;
            clientSet.PESEL = pESEL;
            clientSet.AdressAdressId = adressAdressId;
            return clientSet;
        }
        /// <summary>
        /// There are no comments for Property ClientId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ClientId
        {
            get
            {
                return this._ClientId;
            }
            set
            {
                this.OnClientIdChanging(value);
                this._ClientId = value;
                this.OnClientIdChanged();
                this.OnPropertyChanged("ClientId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ClientId;
        partial void OnClientIdChanging(int value);
        partial void OnClientIdChanged();
        /// <summary>
        /// There are no comments for Property Surname in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Surname
        {
            get
            {
                return this._Surname;
            }
            set
            {
                this.OnSurnameChanging(value);
                this._Surname = value;
                this.OnSurnameChanged();
                this.OnPropertyChanged("Surname");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Surname;
        partial void OnSurnameChanging(string value);
        partial void OnSurnameChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property PESEL in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PESEL
        {
            get
            {
                return this._PESEL;
            }
            set
            {
                this.OnPESELChanging(value);
                this._PESEL = value;
                this.OnPESELChanged();
                this.OnPropertyChanged("PESEL");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PESEL;
        partial void OnPESELChanging(string value);
        partial void OnPESELChanged();
        /// <summary>
        /// There are no comments for Property AdressAdressId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int AdressAdressId
        {
            get
            {
                return this._AdressAdressId;
            }
            set
            {
                this.OnAdressAdressIdChanging(value);
                this._AdressAdressId = value;
                this.OnAdressAdressIdChanged();
                this.OnPropertyChanged("AdressAdressId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _AdressAdressId;
        partial void OnAdressAdressIdChanging(int value);
        partial void OnAdressAdressIdChanged();
        /// <summary>
        /// There are no comments for AdressSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public AdressSet AdressSet
        {
            get
            {
                return this._AdressSet;
            }
            set
            {
                this._AdressSet = value;
                this.OnPropertyChanged("AdressSet");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private AdressSet _AdressSet;
        /// <summary>
        /// There are no comments for PolicySet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<PolicySet> PolicySet
        {
            get
            {
                return this._PolicySet;
            }
            set
            {
                this._PolicySet = value;
                this.OnPropertyChanged("PolicySet");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<PolicySet> _PolicySet = new global::System.Data.Services.Client.DataServiceCollection<PolicySet>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for InsuranceCompanyModel.EmployeeSet in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("EmployeeSet")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class EmployeeSet : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new EmployeeSet object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="login">Initial value of Login.</param>
        /// <param name="password">Initial value of Password.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="surname">Initial value of Surname.</param>
        /// <param name="role">Initial value of Role.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static EmployeeSet CreateEmployeeSet(int ID, string login, string password, string name, string surname, string role)
        {
            EmployeeSet employeeSet = new EmployeeSet();
            employeeSet.Id = ID;
            employeeSet.Login = login;
            employeeSet.Password = password;
            employeeSet.Name = name;
            employeeSet.Surname = surname;
            employeeSet.Role = role;
            return employeeSet;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Login in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Login
        {
            get
            {
                return this._Login;
            }
            set
            {
                this.OnLoginChanging(value);
                this._Login = value;
                this.OnLoginChanged();
                this.OnPropertyChanged("Login");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Login;
        partial void OnLoginChanging(string value);
        partial void OnLoginChanged();
        /// <summary>
        /// There are no comments for Property Password in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Password
        {
            get
            {
                return this._Password;
            }
            set
            {
                this.OnPasswordChanging(value);
                this._Password = value;
                this.OnPasswordChanged();
                this.OnPropertyChanged("Password");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Password;
        partial void OnPasswordChanging(string value);
        partial void OnPasswordChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Surname in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Surname
        {
            get
            {
                return this._Surname;
            }
            set
            {
                this.OnSurnameChanging(value);
                this._Surname = value;
                this.OnSurnameChanged();
                this.OnPropertyChanged("Surname");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Surname;
        partial void OnSurnameChanging(string value);
        partial void OnSurnameChanged();
        /// <summary>
        /// There are no comments for Property Role in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Role
        {
            get
            {
                return this._Role;
            }
            set
            {
                this.OnRoleChanging(value);
                this._Role = value;
                this.OnRoleChanged();
                this.OnPropertyChanged("Role");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Role;
        partial void OnRoleChanging(string value);
        partial void OnRoleChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for InsuranceCompanyModel.HouseSet in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ObjectId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("HouseSet")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ObjectId")]
    public partial class HouseSet : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new HouseSet object.
        /// </summary>
        /// <param name="objectId">Initial value of ObjectId.</param>
        /// <param name="year">Initial value of Year.</param>
        /// <param name="size">Initial value of Size.</param>
        /// <param name="type">Initial value of Type.</param>
        /// <param name="policy_PolicyId">Initial value of Policy_PolicyId.</param>
        /// <param name="adressSet_AdressId">Initial value of AdressSet_AdressId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static HouseSet CreateHouseSet(int objectId, int year, int size, string type, int policy_PolicyId, int adressSet_AdressId)
        {
            HouseSet houseSet = new HouseSet();
            houseSet.ObjectId = objectId;
            houseSet.Year = year;
            houseSet.Size = size;
            houseSet.Type = type;
            houseSet.Policy_PolicyId = policy_PolicyId;
            houseSet.AdressSet_AdressId = adressSet_AdressId;
            return houseSet;
        }
        /// <summary>
        /// There are no comments for Property ObjectId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ObjectId
        {
            get
            {
                return this._ObjectId;
            }
            set
            {
                this.OnObjectIdChanging(value);
                this._ObjectId = value;
                this.OnObjectIdChanged();
                this.OnPropertyChanged("ObjectId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ObjectId;
        partial void OnObjectIdChanging(int value);
        partial void OnObjectIdChanged();
        /// <summary>
        /// There are no comments for Property Year in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Year
        {
            get
            {
                return this._Year;
            }
            set
            {
                this.OnYearChanging(value);
                this._Year = value;
                this.OnYearChanged();
                this.OnPropertyChanged("Year");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Year;
        partial void OnYearChanging(int value);
        partial void OnYearChanged();
        /// <summary>
        /// There are no comments for Property Size in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Size
        {
            get
            {
                return this._Size;
            }
            set
            {
                this.OnSizeChanging(value);
                this._Size = value;
                this.OnSizeChanged();
                this.OnPropertyChanged("Size");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Size;
        partial void OnSizeChanging(int value);
        partial void OnSizeChanged();
        /// <summary>
        /// There are no comments for Property Type in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Type
        {
            get
            {
                return this._Type;
            }
            set
            {
                this.OnTypeChanging(value);
                this._Type = value;
                this.OnTypeChanged();
                this.OnPropertyChanged("Type");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Type;
        partial void OnTypeChanging(string value);
        partial void OnTypeChanged();
        /// <summary>
        /// There are no comments for Property Policy_PolicyId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Policy_PolicyId
        {
            get
            {
                return this._Policy_PolicyId;
            }
            set
            {
                this.OnPolicy_PolicyIdChanging(value);
                this._Policy_PolicyId = value;
                this.OnPolicy_PolicyIdChanged();
                this.OnPropertyChanged("Policy_PolicyId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Policy_PolicyId;
        partial void OnPolicy_PolicyIdChanging(int value);
        partial void OnPolicy_PolicyIdChanged();
        /// <summary>
        /// There are no comments for Property AdressSet_AdressId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int AdressSet_AdressId
        {
            get
            {
                return this._AdressSet_AdressId;
            }
            set
            {
                this.OnAdressSet_AdressIdChanging(value);
                this._AdressSet_AdressId = value;
                this.OnAdressSet_AdressIdChanged();
                this.OnPropertyChanged("AdressSet_AdressId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _AdressSet_AdressId;
        partial void OnAdressSet_AdressIdChanging(int value);
        partial void OnAdressSet_AdressIdChanged();
        /// <summary>
        /// There are no comments for AdressSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public AdressSet AdressSet
        {
            get
            {
                return this._AdressSet;
            }
            set
            {
                this._AdressSet = value;
                this.OnPropertyChanged("AdressSet");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private AdressSet _AdressSet;
        /// <summary>
        /// There are no comments for PolicySet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public PolicySet PolicySet
        {
            get
            {
                return this._PolicySet;
            }
            set
            {
                this._PolicySet = value;
                this.OnPropertyChanged("PolicySet");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private PolicySet _PolicySet;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for InsuranceCompanyModel.PolicySet in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PolicyId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("PolicySet")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("PolicyId")]
    public partial class PolicySet : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new PolicySet object.
        /// </summary>
        /// <param name="policyId">Initial value of PolicyId.</param>
        /// <param name="duration">Initial value of Duration.</param>
        /// <param name="startDate">Initial value of StartDate.</param>
        /// <param name="endDate">Initial value of EndDate.</param>
        /// <param name="objectType">Initial value of ObjectType.</param>
        /// <param name="clientClientId">Initial value of ClientClientId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static PolicySet CreatePolicySet(int policyId, int duration, global::System.DateTime startDate, global::System.DateTime endDate, string objectType, int clientClientId)
        {
            PolicySet policySet = new PolicySet();
            policySet.PolicyId = policyId;
            policySet.Duration = duration;
            policySet.StartDate = startDate;
            policySet.EndDate = endDate;
            policySet.ObjectType = objectType;
            policySet.ClientClientId = clientClientId;
            return policySet;
        }
        /// <summary>
        /// There are no comments for Property PolicyId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int PolicyId
        {
            get
            {
                return this._PolicyId;
            }
            set
            {
                this.OnPolicyIdChanging(value);
                this._PolicyId = value;
                this.OnPolicyIdChanged();
                this.OnPropertyChanged("PolicyId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _PolicyId;
        partial void OnPolicyIdChanging(int value);
        partial void OnPolicyIdChanged();
        /// <summary>
        /// There are no comments for Property Duration in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Duration
        {
            get
            {
                return this._Duration;
            }
            set
            {
                this.OnDurationChanging(value);
                this._Duration = value;
                this.OnDurationChanged();
                this.OnPropertyChanged("Duration");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Duration;
        partial void OnDurationChanging(int value);
        partial void OnDurationChanged();
        /// <summary>
        /// There are no comments for Property StartDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime StartDate
        {
            get
            {
                return this._StartDate;
            }
            set
            {
                this.OnStartDateChanging(value);
                this._StartDate = value;
                this.OnStartDateChanged();
                this.OnPropertyChanged("StartDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _StartDate;
        partial void OnStartDateChanging(global::System.DateTime value);
        partial void OnStartDateChanged();
        /// <summary>
        /// There are no comments for Property EndDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime EndDate
        {
            get
            {
                return this._EndDate;
            }
            set
            {
                this.OnEndDateChanging(value);
                this._EndDate = value;
                this.OnEndDateChanged();
                this.OnPropertyChanged("EndDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _EndDate;
        partial void OnEndDateChanging(global::System.DateTime value);
        partial void OnEndDateChanged();
        /// <summary>
        /// There are no comments for Property ObjectType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ObjectType
        {
            get
            {
                return this._ObjectType;
            }
            set
            {
                this.OnObjectTypeChanging(value);
                this._ObjectType = value;
                this.OnObjectTypeChanged();
                this.OnPropertyChanged("ObjectType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ObjectType;
        partial void OnObjectTypeChanging(string value);
        partial void OnObjectTypeChanged();
        /// <summary>
        /// There are no comments for Property ClientClientId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ClientClientId
        {
            get
            {
                return this._ClientClientId;
            }
            set
            {
                this.OnClientClientIdChanging(value);
                this._ClientClientId = value;
                this.OnClientClientIdChanged();
                this.OnPropertyChanged("ClientClientId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ClientClientId;
        partial void OnClientClientIdChanging(int value);
        partial void OnClientClientIdChanged();
        /// <summary>
        /// There are no comments for CarSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<CarSet> CarSet
        {
            get
            {
                return this._CarSet;
            }
            set
            {
                this._CarSet = value;
                this.OnPropertyChanged("CarSet");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<CarSet> _CarSet = new global::System.Data.Services.Client.DataServiceCollection<CarSet>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for ClientSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ClientSet ClientSet
        {
            get
            {
                return this._ClientSet;
            }
            set
            {
                this._ClientSet = value;
                this.OnPropertyChanged("ClientSet");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private ClientSet _ClientSet;
        /// <summary>
        /// There are no comments for HouseSet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<HouseSet> HouseSet
        {
            get
            {
                return this._HouseSet;
            }
            set
            {
                this._HouseSet = value;
                this.OnPropertyChanged("HouseSet");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<HouseSet> _HouseSet = new global::System.Data.Services.Client.DataServiceCollection<HouseSet>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for InsuranceCompanyModel.sysdiagrams in the schema.
    /// </summary>
    /// <KeyProperties>
    /// diagram_id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("sysdiagrams")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("diagram_id")]
    public partial class sysdiagrams : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new sysdiagrams object.
        /// </summary>
        /// <param name="name">Initial value of name.</param>
        /// <param name="principal_id">Initial value of principal_id.</param>
        /// <param name="diagram_id">Initial value of diagram_id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static sysdiagrams Createsysdiagrams(string name, int principal_id, int diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }
        /// <summary>
        /// There are no comments for Property name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this._name = value;
                this.OnnameChanged();
                this.OnPropertyChanged("name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _name;
        partial void OnnameChanging(string value);
        partial void OnnameChanged();
        /// <summary>
        /// There are no comments for Property principal_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int principal_id
        {
            get
            {
                return this._principal_id;
            }
            set
            {
                this.Onprincipal_idChanging(value);
                this._principal_id = value;
                this.Onprincipal_idChanged();
                this.OnPropertyChanged("principal_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _principal_id;
        partial void Onprincipal_idChanging(int value);
        partial void Onprincipal_idChanged();
        /// <summary>
        /// There are no comments for Property diagram_id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int diagram_id
        {
            get
            {
                return this._diagram_id;
            }
            set
            {
                this.Ondiagram_idChanging(value);
                this._diagram_id = value;
                this.Ondiagram_idChanged();
                this.OnPropertyChanged("diagram_id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _diagram_id;
        partial void Ondiagram_idChanging(int value);
        partial void Ondiagram_idChanged();
        /// <summary>
        /// There are no comments for Property version in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> version
        {
            get
            {
                return this._version;
            }
            set
            {
                this.OnversionChanging(value);
                this._version = value;
                this.OnversionChanged();
                this.OnPropertyChanged("version");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _version;
        partial void OnversionChanging(global::System.Nullable<int> value);
        partial void OnversionChanged();
        /// <summary>
        /// There are no comments for Property definition in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] definition
        {
            get
            {
                if ((this._definition != null))
                {
                    return ((byte[])(this._definition.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OndefinitionChanging(value);
                this._definition = value;
                this.OndefinitionChanged();
                this.OnPropertyChanged("definition");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _definition;
        partial void OndefinitionChanging(byte[] value);
        partial void OndefinitionChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
